name: dart_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: yuraantonov11 <yuraantonov11@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  teledart: ^0.0.34
  http: ^0.12.0+2
  html: ^0.14.0+3
  test: ^1.9.4

dev_dependencies:
  pedantic: ^1.8.0
