name: dart_server
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: yuraa <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  teledart: ^0.0.34

dev_dependencies:
  pedantic: ^1.8.0
